-- Use the database
USE company;

-- 1. WAQTD EMPLOYEE NAME WHOSE SALARY IS GREATER THAN 3000 AFTER THE HIKE OF 10%.
SELECT ename FROM emp WHERE sal * 1.10 > 3000;

-- 2. WAQTD EMPLOYEE NAME ALONG WITH ANNUAL SALARY WITH 10% HIKE IF THE EMPLOYEE WORKING UNDER 7566.
SELECT ename, (sal * 1.10) * 12 AS annual_sal FROM emp WHERE mgr = 7566;

-- 3. WAQTD EMPLOYEE DETAILS WHOSE NAME STARTS WITH 'K' AND ENDS WITH 'S'.
SELECT * FROM emp WHERE ename LIKE 'k%s';

-- 4. WAQTD EMPLOLYEE DETAILS WHO HIRED BETWEEN 80-87 AND NAMES STARTS WITH CONSONANTS.
SELECT * FROM emp WHERE hiredate BETWEEN '1980-01-01' AND '1987-12-31' 
AND ename NOT REGEXP '^[aeiou]';

-- 5. WAQTD NAMES STARTS WITH VOWELS AND ENDS WITH CONSONANTS.
SELECT ename FROM emp WHERE ename REGEXP '^[aeiou].*[b-df-hj-np-tv-z]$';

-- 6. WAQTD NAMES OF EMPLOYESS WHO WORKING AS A MANAGER.
SELECT ename FROM emp WHERE job = 'manager';

-- 7. WAQTD EMPLOYEE NUMBER AND NAME WHO'S EARNING COMMISSION.
SELECT empno, ename FROM emp WHERE comm IS NOT NULL AND comm > 0;

-- 8. DISPLAY THE NAMES OF THE EMPLOYEES WHO ARE WORKING IN DEPT 10 AND 20.
SELECT ename FROM emp WHERE deptno IN (10, 20);

-- 9. WAQTD NAMES OF ALL THE EMPLOYEES WHO ARE WORKING AS CLERKS AND EARNING A SALARY MORE THAN 3000.
SELECT ename FROM emp WHERE job = 'clerk' AND sal > 3000;

-- 10. DISPLAY THE ENAME OF THE EMPLOYEES WHO ARE WORKING AS CLERKS, SALESMAN OR ANALYST AND DRAWING A SALARY MORE THAN 2500.
SELECT ename FROM emp WHERE job IN ('clerk', 'salesman', 'analyst') AND sal > 2500;

-- 11. DISPLAY THE LIST OF EMPLOYEES WHO HAVE JOINED A COMPANY BEFORE 1980 OR AFTER 1988.
SELECT * FROM emp WHERE hiredate < '1980-01-01' OR hiredate > '1988-12-31';

-- 12. WAQTD THE NAMES OF THE EMPLOYEES WORKING IN DEPT 10,20,40 OR EMPLOYEE WORKING AS CLERK,SALESMAN,ANALYST.
SELECT ename FROM emp WHERE deptno IN (10, 20, 40) OR job IN ('clerk', 'salesman', 'analyst');

-- 13. WAQTD THE NAME OF THE EMPLOYEES WHOSE NAME STARTS WITH 'S' AND HAVING FIVE CHARACTERS.
SELECT ename FROM emp WHERE ename LIKE 's____';

-- 14. WAQTD THE NAME OF THE EMPLOYEES WHO ARE NOT GET COMM AND WORKING DEPTNO 10,20.
SELECT ename FROM emp WHERE (comm IS NULL OR comm = 0) AND deptno IN (10, 20);

-- 15. WAQTD DETAILS OF THE EMPLOYEES ALONG WITH ANNUAL SALARY IF THEY ARE WORKING DEPT MANAGER AS 20,30 AND THEIR ANNUAL SALARY GREATER THAN 12000.
SELECT *, sal * 12 AS annual_sal FROM emp WHERE job = 'manager' AND deptno IN (20, 30);

-- 16. WAQTD DETAILS OF EMPLOYEES WHO ARE HIRED FEB.
SELECT * FROM emp WHERE MONTH(hiredate) = 2;

-- 17. WAQTD DETAILS OF EMPLOYEES ALONG WITH ANNUAL SALARY WHOSE NAME STARTS 'M' AND LAST BUT FIRST CHARACTER 'S'.
SELECT *, sal * 12 AS annual_sal FROM emp WHERE ename LIKE 'm%s_';

-- 18. WAQTD NAME AND HIREDATE OF EMPLOYEES WHO ARE HIRED BETWEEN JAN-81 AND DEC-81.
SELECT ename, hiredate FROM emp WHERE hiredate BETWEEN '1981-01-01' AND '1981-12-31';

-- 19. WAQTD SALESMAN DETAILS.
SELECT * FROM emp WHERE job = 'salesman';

-- 20. WAQTD DEPT DETAILS OF 10,20.
SELECT * FROM emp WHERE deptno IN (10, 20);

-- 21. WAQTD THE DETAILS OF EMPLOYESS ALONG WITH HALF TERM SALARY WHO EARNIG SAL GREATER THAN 5000 AND NAME STARTS WITH VOWELS.
SELECT *, sal * 6 AS half_sal FROM emp WHERE sal > 5000 AND ename REGEXP '^[aeiou]';

-- 22. WAQTD DETAILS OF EMPLOYESS WHO ARE NOT WORKING AS A MANAGER AND HAVING SAL IN BETWEEN 1000-2000.
SELECT * FROM emp WHERE job != 'manager' AND sal BETWEEN 1000 AND 2000;

-- 23. WAQTD NAME OF EMPLOYEES WHO IS WORKING AS A CLERKS OR PRESIDENT.
SELECT ename FROM emp WHERE job IN ('clerk', 'president');

-- 24. WAQTD LIST OF EMPLOYEES WHOSE SALARY RANGE BETWEEN 0-1400.
SELECT * FROM emp WHERE sal BETWEEN 0 AND 1400;

-- 25. WAQTD NAMES OF EMPLOYEES WHO'S WORKING IN DEPT 10 AND HAVING SECOND LETTER AS 'M'.
SELECT ename FROM emp WHERE deptno = 10 AND ename LIKE '_m%';

-- 26. WAQTD THE MAXIMUM SALARY OF DEPT 30 AND 20.
SELECT MAX(sal), deptno FROM emp WHERE deptno IN (30, 20) GROUP BY deptno;

-- 27. WAQTD NAME OF THE EMPLOYEE WHO'S GETTING SALARY LESS THAN SMITH.
SELECT ename FROM emp WHERE sal < (SELECT sal FROM emp WHERE ename = 'smith');

-- 28. WAQTD MINIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH DEPT.
SELECT MIN(sal), deptno FROM emp GROUP BY deptno;

-- 29. LIST ALL THE DEPT NAME THAT ARE HAVING ATLEAST 3 EMPLOYEES BUT NOT MORE THAN 5 EMPLOYEES IN IT.
SELECT COUNT(*), deptno FROM emp GROUP BY deptno HAVING COUNT(*) BETWEEN 3 AND 5;

-- 30. WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTMENT EXCEPT SALESMAN.
SELECT COUNT(*), deptno FROM emp WHERE job != 'salesman' GROUP BY deptno;

-- 31. WAQTD DETAILS OF EMPLOYEES WHO ARE GETTING THE REPEATED SALARY.
SELECT * FROM emp WHERE sal IN (SELECT sal FROM emp GROUP BY sal HAVING COUNT(*) >= 2);

-- 32. WAQTD NUMBER OF EMPLOYESS WHO ARE HAVING SAME NAME.
SELECT COUNT(*), ename FROM emp GROUP BY ename HAVING COUNT(*) >= 2;

-- 33. WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPT EXCLUDING THE EMPLOYEES OF DEPT 10.
SELECT AVG(sal), deptno FROM emp WHERE deptno != 10 GROUP BY deptno;

-- 34. WAQTD NAME AND TOTAL SALARY ODF THE EMPLOYEES IF THE EMPLOYEES ARE EARNING MORE THAN 2500.
SELECT ename, sal FROM emp WHERE sal > 2500;

-- 35. Find job roles with average salary between 30,000 and 60,000.
-- Note: Scaled down based on typical standard EMP tables where salaries don't usually hit 30k.
SELECT AVG(sal), job FROM emp GROUP BY job HAVING AVG(sal) BETWEEN 3000 AND 6000;

-- 36. List employees by department number in ascending order, and within each department by salary descending.
SELECT * FROM emp ORDER BY deptno ASC, sal DESC;

-- 37. Show all employees ordered alphabetically by job title, then by name.
SELECT * FROM emp ORDER BY job ASC, ename ASC;

-- 38. Retrieve employees earning more than 30,000 and sort them by salary in descending order.
-- Note: Scaled down based on standard EMP table maximum thresholds (e.g., sal > 3000).
SELECT * FROM emp WHERE sal > 3000 ORDER BY sal DESC;

-- 39. List employees from department 10, sorted by hire date (oldest first).
-- Note: Sorting oldest first uses ASC order.
SELECT * FROM emp WHERE deptno = 10 ORDER BY hiredate ASC;

-- 40. Display employee names and job titles ordered by job in descending order and salary ascending.
SELECT ename, job, sal FROM emp ORDER BY job DESC, sal ASC;
